### ISSUE TITLE
Bot permanently running at 100% CPU

### ISSUE THREAD

**Issue by drakes00** [jilv220/freqtrade-stuff#1]
Hi,

Thanks a lot for your strategies.
My BB_RPB_TSL_RNG bots are constantly running at 100% CPU with like no IDLE.
Even resource heavy strats such as NFI are less than 10% CPU on htop.

Do you have an idea why BB_RPB_TSL_RNG is the only one doing it?

King regards,

EDIT: Thanks to the discord, adding `process_only_new_candles = True` would help CPU (such as in MultiMA_TSL).
Would it have a big impact on the strat?

**Comment by jilv220** [comment]
There won't be any impact on the strat. Thank you for the feedback. I have fixed the strat.
